### ISSUE TITLE
Add integration tests to test connectivity with DBAL and actual databases

### ISSUE THREAD

**Issue by aphlor** [wethersherbs/pineapple#17]
At present, the unit test coverage will give confidence in the _framework_ for being able to operate successfully without errors, however it will not give confidence in being able to operate successfully for real-world connectivity. Add tests to cover at the very least MySQL.

**Comment by borb** [comment]
We have a test in progress for testing the DBAL driver with the sqlite in-memory database.

**Comment by aphlor** [comment]
We're done.
