### ISSUE TITLE
Test suite not completing

### ISSUE THREAD

**Issue by borb** [wethersherbs/pineapple#2]
Test suite currently failing in `deeper-refactor`.

**Comment by aphlor** [comment]
I don't believe this is currently the situation; there are warnings generated for some empty test stubs. I do not believe in using skelgen to generate test stubs as the empty methods qualify as "test present". Warnings do not constitute failure, however they do not give confidence in a good suite of tests.

**Comment by borb** [comment]
Test suite is now passing without warnings. Coverage is at 89%. Closing, all efforts to maintain no warnings & successful completion will be made in future.
