### ISSUE TITLE
Restore the plain PDO driver

### ISSUE THREAD

**Issue by borb** [wethersherbs/pineapple#22]
The DBAL driver does not offer full compatibility with PDO in that some methods are unavailable. This may extend to other areas of use. We have a PDO driver available, and it would be handy to include that in the package, since Doctrine DBAL may not be to everyone's liking.

**Comment by aphlor** [comment]
The driver is back, the tests are passing, the next trick will be getting two forms of error handling working smoothly together.

See http://php.net/manual/en/pdo.error-handling.php for details.

**Comment by aphlor** [comment]
Not so much "together", but working in such a manner we can handle errors in both modes.

**Comment by aphlor** [comment]
Driver is restored, coverage complete, tests pass.
