### ISSUE TITLE
Naming conventions are not PSR-2

### ISSUE THREAD

**Issue by borb** [wethersherbs/pineapple#3]
Make namespace/class/property/method naming compliant with PSR-2.

**Comment by aphlor** [comment]
Particularly 'DB' versus 'Db'

**Comment by i-am-tom** [comment]
```
use Pineapple\DB;
use Doctrine\DBAL\Connection as DBALConnection;
```

It looks as though Doctrine doesn't find this to be too important; would the change be a needless diversion from the original library format of "DB"?

**Comment by borb** [comment]
Done.
