### ISSUE TITLE
Missing methods In DB_common

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#33]
The following methods are inherited in all the drivers from DB_common in PEAR DB but I could not see an implementation for with the new drivers.

```
createSequence()
dropSequence()
executeEmulateQuery()
getListOf()
getSequenceName()
getSpecialQuery()
getTables()
modifyLimitQuery()
modifyQuery()
nextId()
quote()
quoteBoolean()
quoteFloat()
quoteString()
toString()
_checkManip()
_convertNullArrayValuesToEmpty()
_rtrimArrayValues()
__wakeup()
```

**Comment by aphlor** [comment]
These have been either removed due to deprecation or moved to pineapple-compat. In either case, this is not actually a bug.
