### ISSUE TITLE
PDO Query Buffering

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#38]
You turn query buffering off on this [line](https://github.com/wethersherbs/pineapple/blob/b3b46fc46efa20b706aee8e9622c8662a8fa3ef1/src/DB/Driver/PdoDriver.php#L121) however nothing ever happens after this. So all queries are always buffered.

**Comment by aphlor** [comment]
Playschool programming error. Please caffeinate developer and try again.

**Comment by aphlor** [comment]
Fixed!
