### ISSUE TITLE
Crazy docblocks

### ISSUE THREAD

**Issue by borb** [wethersherbs/pineapple#4]
The docblocks are formatted in unusual ways.

**Comment by i-am-tom** [comment]
I *think* this is something not worth worrying about?

**Comment by borb** [comment]
The docblocks are correct _enough_, in that anyone using atom-autocomplete-php or PhpStorm will be seeing the same docblocks that they have at present in PEAR and DB.

**Comment by borb** [comment]
However phan notes several issues regarding inconsistencies between which values are passed in and how they're declared. We should fix them at some point but it's not critical to the use of the module.

We're encouraging people to use Dbal/PDO in future, not nurture future use of Pineapple. It's effectively end-of-life before it has even started.

**Comment by borb** [comment]
Sorted.
