### ISSUE TITLE
`tableInfo()` Error with PDO

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#40]
**Note**: only tested with PDO driver

When calls are made to the `tableInfo()` method instead of returning the table info, you get an instance of `Pineapple\DB\Error` with the error code of `int(-1)`

**Comment by aphlor** [comment]
`int(-1)` maps to `DB::DB_ERROR`, for reference.

**Comment by aphlor** [comment]
Great, so now the integration test for using PDO with sqlite in-memory works fine, but now I have both failures using `PdoDriver` with real MySQL and different results with sqlite in-memory on a PHP 5.6 environment. Still investigating.

**Comment by aphlor** [comment]
I can't be sure of the exact details of how you reproduced this fault, but I have not been able to make `tableInfo()` fail the way you have described. I have however noticed some discrepancies between what we do and between what PEAR DB does, and have corrected those faults and made the output like-for-like with the available data.
