### ISSUE TITLE
DB::isManip

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#43]
According to the PEAR manual:

```
Examples of data manipulation queries are INSERT, UPDATE and DELETE. Examples of data definition queries are CREATE, DROP, ALTER, GRANT, REVOKE.
```

However all of the above examples return `TRUE`.

**Comment by aphlor** [comment]
I note your comment, however:

1. Changing this behaviour may break backward compatibility.
   This has been around for a while. This may constitute a more wide-ranging effect than simple refactoring of some values or calls to methods, which is one thing we're trying to avoid.
2. Not just MySQL, but this a multi-platform issue. Some databases (Oracle, for example) can and _do_ transact the creation of a table. The alteration of a table. Even dropping a table.
3. This code is like-for-like with the upstream PEAR DB. See [upstream](https://github.com/pear/DB/blob/trunk/DB.php#L629) and [pineapple's `isManip`](https://github.com/wethersherbs/pineapple/blob/dev-0.3.x/src/DB/Driver/Common.php#L1805), which are identical save for a couple of missing manipulation cases.

Sorry, but in view of this, I'm marking this as wontfix and closing.
