### ISSUE TITLE
DB_common `autoPrepare()`

### ISSUE THREAD

**Issue by Tohmua** [wethersherbs/pineapple#44]
This returns int(0) rather than a resource

**Comment by aphlor** [comment]
Regardless of what the docblock for `DB_common::prepare` says about the return type, it speaks lies. See [the upstream code](https://github.com/pear/DB/blob/trunk/DB/common.php#L828).

Probably can't fix this. May be able to, but honestly it's not that big of a deal. Going to mark this wontfix.
