### ISSUE TITLE
`PdoCommonMethods::lastInsertId` tries to translate a non-ANSI code using ANSI mechanism during unsupported call

### ISSUE THREAD

**Issue by aphlor** [wethersherbs/pineapple#54]
`PdoCommonMethods::lastInsertId`'s exception-to-PEAR-Error mechanism attempts to translate an exception code into a PEAR error code via the ANSI SQL error code mechanism (`getNativeErrorCode`). The code is:

```php
        try {
            $sequenceValue = $this->connection->lastInsertId($sequence);
            // can't "generate" a fault in a platform within which sequences are supported, so...
            // @codeCoverageIgnoreStart
        } catch (PDOException $sequenceException) {
            return $this->raiseError($this->getNativeErrorCode($sequenceException->getCode()));
            // @codeCoverageIgnoreEnd
        }
```

However, two things are evident:

1. `getCode` may well be returning nothing; it's a numerical-only code, and ANSI SQL error codes are alphanumeric.
2. It's probably correct to call `$this->connection->errorCode()` in the catch block to obtain the correct code. Catching the exception is merely acknowledging the mistake, the error code mechanism is that of PDO, not the exception.

**Comment by borb** [comment]
Having read the documentation, this appears not to be the case: `getCode` in the case of `Exception` is an integer owing to protected property `$code` being an `int`, but in the case of `PDOException` this is a string. The assumption is invalid here. Closing.
